### ISSUE TITLE
postgres text search not working properly

### ISSUE THREAD

**Issue by carletex** [amy-jung/collectivedaoarchives.catalog#28]
e.g. https://collectivedaoarchives-catalog.vercel.app/search?q=governance

![image](https://github.com/amy-jung/collectivedaoarchives.catalog/assets/2486142/331934d3-8c6f-42e8-b338-ec6cdd457e8c)

For some words (that exist in a lot of the records) search doesn't seem to work.

Let's find out what could be the issue.

**Comment by carletex** [comment]
Since merging #32 I noticed that something **might be wrong with the search query**, which is related to this issue.

e.g. 

https://collectivedaoarchives-catalog.vercel.app/search?q=governance

![image](https://github.com/amy-jung/collectivedaoarchives.catalog/assets/2486142/463a7794-0460-45d1-bafb-b1ae5ad19a74)

Page 2 works: https://collectivedaoarchives-catalog.vercel.app/search?q=governance&page=2
![image](https://github.com/amy-jung/collectivedaoarchives.catalog/assets/2486142/55500ed4-75a4-4349-a686-a5832812f756)

cc @damianmarti

**Comment by damianmarti** [comment]
@carletex thanks!! I will take a look!

**Comment by damianmarti** [comment]
@carletex It's weird. It's working right on my local env. Does it work ok in your local environment?

**Comment by carletex** [comment]
@damianmarti yes, the same error was showing on my local environment.

I fixed here: #33

**Comment by damianmarti** [comment]
> @damianmarti yes, the same error was showing on my local environment.
> 
> I fixed here: #33

Thanks!!
