### ISSUE TITLE
Submit record/s page + logic

### ISSUE THREAD

**Issue by carletex** [amy-jung/collectivedaoarchives.catalog#40]
We need to store the submitted URLs in the database.

@damianmarti we could:
1. Add a "draft" or "approved" (the opposite) flag in the records table. We'd have to do a prisma "migration"
2. When people submit a URL it will be stored there with the flag draft = true (or approved "false")
3. For now, we manually go, add the required field + tweak + approve (future: crawler/AI will populate the fields for us)

![image](https://github.com/amy-jung/collectivedaoarchives.catalog/assets/2486142/9062bb20-08b3-421b-bbf9-b8642fe9b235)

---

@amy-jung since we are only asking for URLs (it'll be a CSV file with just one column :D), another idea will be to just have a textarea, where you just paste the URLS (one per line). What do you think?

**Comment by damianmarti** [comment]
I think is better to have the textarea and add a note like "One link per line"

**Comment by amy-jung** [comment]
My concern is that there's more opportunity for mistakes with a textarea, but I see what you mean if the submissions go straight into our records database.

Additionally, my feeling is that users already save links in some google sheets type of thing, but I'm going to do a quick ask with users.

**Comment by damianmarti** [comment]
I think that if the user can upload a csv file, will try to upload any csv without taking too much care of the format. But if we ask for links, one link for each line in a textarea, the user has to think a little about it before pasting the content.

Anyway, we can start with one option and then add the other option too.

**Comment by carletex** [comment]
We can work on the save logic until we decide CSV vs textarea.

----

As discussed with @damianmarti we could:

1. Create a different table (will only contain the submitted URLs)

or

2. Save the in the same Google Sheet / notion

In any case, it's a temporary storage, since for now, we'd have to manually parse the URL and populate all the fields.

---

Also, do we want them to sign (with their wallet) the submission? Created #43 

cc @amy-jung

**Comment by amy-jung** [comment]
- Add signing with submission

Start building the single URL + textarea logic then Amy will do some user testing and then we can decide on CSV
1. Update new URLs directly to database > maybe new table with a tag (filter status)
2. Give Amy access to database
3. Carlos / Damu will walk Amy through how to add/update
4. Do a test

- For CSV: Would include a link to a template. What would we do if CSVs aren’t submitted correctly? > parse data

**Comment by damianmarti** [comment]
@amy-jung @carletex Should this feature be added to the **Contribute** page or should I create a new page?

**Comment by carletex** [comment]
The current Contribute page is just a placeholder, so you can use it for this issue. Thanks Damu! <3

**Comment by damianmarti** [comment]
> When we sign a submission, does it makes sense to make it an attestation? I'm wary of scope creep so let me know if that's outside this scope!

I'm not sure. Maybe we can thing about it later...

**Comment by damianmarti** [comment]
PR opened with an initial contribution page https://github.com/amy-jung/collectivedaoarchives.catalog/pull/50

**Comment by amy-jung** [comment]
Closing this and will reopen / create a new one if we get input on CSVs
